# Generated by Django 5.2.18 on 2026-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pageview', 'Page view'), ('mode_switch', 'Mode switch'), ('theme_switch', 'Theme switch'), ('game_play', 'Game play'), ('resume_download', 'Resume download'), ('outbound_click', 'Outbound link click'), ('terminal_command', 'Terminal command')], db_index=True, max_length=30)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('mode', models.CharField(blank=True, max_length=20)),
                ('theme', models.CharField(blank=True, max_length=10)),
                ('device', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('tablet', 'Tablet'), ('desktop', 'Desktop')], max_length=10)),
                ('referrer', models.CharField(blank=True, help_text='Referrer host only', max_length=200)),
                ('visitor_hash', models.CharField(db_index=True, max_length=64)),
                ('props', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='analytics_e_kind_544e39_idx')],
            },
        ),
    ]
