# Generated by Django 5.2.18 on 2026-10-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text='Icon key used by the frontend', max_length=40)),
                ('items', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('platform', models.CharField(choices=[('github', 'GitHub'), ('linkedin', 'LinkedIn'), ('x', 'X / Twitter'), ('email', 'Email'), ('website', 'Website'), ('leetcode', 'LeetCode'), ('kaggle', 'Kaggle'), ('medium', 'Medium'), ('other', 'Other')], default='other', max_length=20)),
                ('label', models.CharField(max_length=80)),
                ('url', models.CharField(help_text='https://… or mailto:…', max_length=500)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(default='Your Name', max_length=120)),
                ('headline', models.CharField(blank=True, max_length=200)),
                ('tagline', models.CharField(blank=True, help_text='One-liner under the name', max_length=300)),
                ('roles', models.JSONField(blank=True, default=list, help_text='Rotating role titles for the hero animation')),
                ('bio', models.TextField(blank=True, help_text='Short plain-text bio (2-3 sentences)')),
                ('about', models.TextField(blank=True, help_text='Markdown')),
                ('philosophy', models.TextField(blank=True, help_text='Markdown: engineering philosophy')),
                ('location', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('availability', models.CharField(blank=True, help_text='e.g. Open to SDE roles', max_length=200)),
                ('is_available', models.BooleanField(default=True)),
                ('avatar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ResumeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="e.g. 'AI Systems — Oct 2026'", max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
