# Generated by Django 5.2.18 on 2026-10-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='journey',
            field=models.JSONField(blank=True, default=list, help_text="Ordered career stages, drawn as the hero's profiler-style trace"),
        ),
    ]
