# Generated by Django 5.2.18 on 2026-10-08 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(max_length=5000)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('visitor_hash', models.CharField(blank=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('source_mode', models.CharField(blank=True, help_text='UI mode used to send', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
