# Generated by Django 5.2.18 on 2026-10-08 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('is_enabled', models.BooleanField(default=True)),
                ('max_score_rate', models.FloatField(default=50.0, help_text='Upper bound of points per second used to reject impossible scores')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=24)),
                ('score', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('session_nonce', models.CharField(max_length=32, unique=True)),
                ('visitor_hash', models.CharField(blank=True, max_length=64)),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden by the owner (moderation)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='games.game')),
            ],
            options={
                'ordering': ['-score', 'created_at'],
                'indexes': [models.Index(fields=['game', '-score'], name='games_score_game_id_3b22ba_idx')],
            },
        ),
    ]
