# Generated by Django 5.2.18 on 2026-10-08 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media_library', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('key', models.CharField(choices=[('hero', 'Hero'), ('about', 'About'), ('focus', 'Current focus'), ('experience', 'Experience'), ('projects', 'Projects'), ('skills', 'Skills'), ('education', 'Education'), ('achievements', 'Leadership & achievements'), ('blog', 'Writing'), ('arcade', 'Arcade'), ('contact', 'Contact')], max_length=20, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SiteConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('site_title', models.CharField(default='Portfolio', max_length=120)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('default_mode', models.CharField(choices=[('simple', 'Simple'), ('terminal', 'Terminal'), ('3d', '3D')], default='simple', max_length=10)),
                ('default_theme', models.CharField(choices=[('system', 'Follow system'), ('dark', 'Dark'), ('light', 'Light')], default='system', max_length=10)),
                ('accent_color', models.CharField(default='#7c5cff', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a hex colour like #7c5cff')])),
                ('terminal_hostname', models.CharField(default='guest@portfolio', max_length=40)),
                ('sound_default_on', models.BooleanField(default=False)),
                ('blog_enabled', models.BooleanField(default=True)),
                ('games_enabled', models.BooleanField(default=True)),
                ('contact_enabled', models.BooleanField(default=True)),
                ('analytics_enabled', models.BooleanField(default=True)),
                ('footer_note', models.CharField(blank=True, max_length=200)),
                ('og_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='media_library.mediaasset')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
