# Generated by Django 5.2.18 on 2026-10-08 12:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0002_seed_sections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='accent_color',
            field=models.CharField(default='#e8a33d', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Use a hex colour like #e8a33d')]),
        ),
    ]
