# Generated by Django 5.2.18 on 2026-10-08 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_config', '0003_accent_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteconfig',
            name='default_mode',
            field=models.CharField(choices=[('simple', 'Simple'), ('terminal', 'Terminal'), ('3d', '3D'), ('drive', 'Drive')], default='simple', max_length=10),
        ),
    ]
